### ISSUE TITLE
Comment cant display on firefox 35 ie 11 chrome 39

### ISSUE THREAD

**Issue by liuliming2008** [JohnMcLear/ep_comments#19]
On windows7 64bit, build the latest version, after comments plugin installed, the comment input dialog is showed. But the comments of the pad dont display.
Steps:
1 build the latest version,  install comment plugin  ,open a pad 
2 click the comment button, they comment input dialog shows
3 type something, click comment to submit
4 the dialog dispear, but the comment not display on the pad content

attachs:
![comment-chrome](https://cloud.githubusercontent.com/assets/1818158/5895532/99fd7a6e-a55d-11e4-8181-12b4f26d5ea8.png)
![comment-firefox](https://cloud.githubusercontent.com/assets/1818158/5895533/99ff305c-a55d-11e4-96ae-3e647ce874ba.png)

**Comment by JohnMcLear** [comment]
Do you still get the javascript errors when ep_comments_page is not installed?  They don't look related.

**Comment by JohnMcLear** [comment]
Tested on beta.etherpad.org and everything is fine.

**Comment by JohnMcLear** [comment]
You do realize you have to select the content you want to comment on before commenting right?

**Comment by liuliming2008** [comment]
Yes, I select content to comment.
After uninstall the ep_comments_page plugin, the error dispear.
I installed the plugin with url/admin/plugins, the url is yundoc.cc:9003
The error means the request url changed from yundoc.cc:9003/socket.io to yundoc.cc/socket.io, and this change realate with the ep_comments_page plugin

**Comment by JohnMcLear** [comment]
@liuliming2008 sounds like your plugin issue is environment specific then.  Without being in your environment I can't fix.  You might want to hire either me or another Etherpad consultant to look into your environment for you.  I cannot connect to your instance.

**Comment by liuliming2008** [comment]
@JohnMcLear
I fixed this in my way.
I find that if the plugin file use relative uri, such as io.connect("/comment"), it will lead to socket.io.js line 1050:
uri = loc.hostname + uri; // var loc = loc || global.location;
The loc.hostname is yundoc.cc, not yundoc.cc:9003.
Here of loc.hostname should be repalced by loc.host or loc.hostname+':'+loc.port.

So I modified the socket.io.js like that, the comment functionality is basically ok now.

But, I find another promblem that:
The pad cant display the synced commets exactly.
Steps:
1 open two client(client-A,client-B) for the same pad pad-n
2 input n comments at client-A
3 client-B show n-1comments on the pad
4 input n+m comments at client-A
5 client-b show n+m-1 comments on the pad
I tested this on the last dev version and beta.etherpad.org, on windows 7 chrome 39, ie 11, firefox 35.

**Comment by liuliming2008** [comment]
And the comment replies will not be updated until input a new replay at local pad.

**Comment by JohnMcLear** [comment]
Please create issues for each problem.  Do not put all issues here.

RE path, can you submit a pull request with a fix?

**Comment by JohnMcLear** [comment]
@liuliming2008 please read this before posting further: http://mclear.co.uk/2015/01/15/how-to-write-a-bug-report/

**Comment by liuliming2008** [comment]
@JohnMcLear  Relaitive path is a socket.io bug I think, I will submit to socket.io.

**Comment by JohnMcLear** [comment]
pushed fix for socket issue.
