### ISSUE TITLE
multi-line comments should collapse when not in focus

### ISSUE THREAD

**Issue by mmccarn** [JohnMcLear/ep_comments#20]
1. Create two lines of text
2. attach a comment that is 3 or more lines long to the first line
3. attach a comment to the second line
When done, the first comment continues below the second comment when the focus is on the second comment:  
![screen shot 2015-01-31 at 8 19 47 am](https://cloud.githubusercontent.com/assets/2945678/5988162/f940ed5e-a921-11e4-8d63-6766328dc217.png)

I think the interface would be cleaner if multi-line comments collapsed to a single line ending in an ellipsis (...) when not in focus (as they do in workflowy, for example)
![screen shot 2015-01-31 at 8 22 37 am](https://cloud.githubusercontent.com/assets/2945678/5988172/5a1db31e-a922-11e4-917d-27a81f0b3555.png)

**Comment by JohnMcLear** [comment]
@mmccarn +1 this, it's an easy CSS fix, something you want to do maybe?

**Comment by mmccarn** [comment]
If it hangs out here long enough I might work on it.  CSS is pretty opaque to me (but if you need help with your foxpro...)

**Comment by JohnMcLear** [comment]
funny you should say that..  I'm thinking about writing an FPS game similar to call of duty in foxpro...  10/10 would recommend?

**Comment by JohnMcLear** [comment]
@mmccarn so I put a fix in for this but it will probably break non-hover devices functionality such as ipads so you will need to deal with that when the complaints land ;)  https://github.com/JohnMcLear/ep_comments/commit/67f0b96d8cba7173024305eeaf4bd15f836e734a
