### ISSUE TITLE
Links to static resources not working 

### ISSUE THREAD

**Issue by jdittrich** [JohnMcLear/ep_comments#23]
**Problem:** After installing the plugin  files like `main.css` and  `jquery.tmpl.min.js` could not be loaded.
**Possible cause:** The concerning etherpad instance does not run on a own domain, but on a subdomain. 
**Possible solution:** After comparing the way *ep_comments* links the resources with the way  other plugins (e.g. [ep_page_view](https://github.com/ether/ep_page_view)) do it, I noted that these other plugins went up a directory before like [`link href="../static/plugins/ep_page_view/static/css/page_view.css" rel="stylesheet`](https://github.com/ether/ep_page_view/blob/b37c7687b7db6a42131b397ef94fcb1d0548fc42/page_view.js) whereas *ep_comments* does not do this: [`/static/plugins/ep_comments_page/static/js/jquery.tmpl.min.js`](<script src="/static/plugins/ep_comments_page/static/js/jquery.tmpl.min.js">). Adding the `../` seems to work on a own domain as well as on a subdomain. 

I can send a pull request implementing this.

**Comment by JohnMcLear** [comment]
I'd accept a pull request with this fix in for sure :) Thanks!

**Comment by JohnMcLear** [comment]
@jdittrich resolved this :) Thanks!
