### ISSUE TITLE
Feature Suggestion: Delete Button for Comments

### ISSUE THREAD

**Issue by jdittrich** [JohnMcLear/ep_comments#24]
**Use Case:** I wrote a comment which is no longer needed or useful. I want to get rid of that comment.

**Current Problems:** 
* Seemingly the whole text on which I commented needs to be removed to remove the comment as well.
* As a user, I may be unaware of the possibility to remove the text to remove the comment

**Solution**
* Like in (probably) familiar office suites, the comment fields can have a "delete" or "x" button to delete them: (Mockup)
![deletecomment](https://cloud.githubusercontent.com/assets/3416487/6284029/5e96585e-b8ec-11e4-832b-8571a3d0f38d.png) 

* Comments could as well be inserted at the end of the text commented on, like an invisible character, which can be deleted. This is how Open Office Writer does it. However, I assume this is far more difficult to implement than the button mentioned above. 

![bildschirmfoto vom 2015-02-20 10 28 01](https://cloud.githubusercontent.com/assets/3416487/6284042/82fd1c3c-b8ec-11e4-94a9-e3175967391b.png) 
(The yellow ▲ is like a character that can be deleted – and with it the comment)

**Comment by JohnMcLear** [comment]
Doable but will need funding / sponsorship as I'm fully booked up doing bug fixes

On 20 Feb 2015 09:39, jdittrich <notifications@github.com> wrote:

Use Case: I wrote a comment which is no longer needed or useful. I want to get rid of that comment.

Current Problems:

  *   Seemingly the whole text on which I commented needs to be removed to remove the comment as well.
  *   As a user, I may be unaware of the possibility to remove the text to remove the comment

Solution

  *   Like in (probably) familiar office suites, the comment fields can have a "delete" or "x" button to delete them: (Mockup)
[deletecomment]<https://cloud.githubusercontent.com/assets/3416487/6284029/5e96585e-b8ec-11e4-832b-8571a3d0f38d.png>

  *   Comments could as well be inserted at the end of the text commented on, like an invisible character, which can be deleted. This is how Open Office Writer does it. However, I assume this is far more difficult to implement than the button mentioned above.

[bildschirmfoto vom 2015-02-20 10 28 01]<https://cloud.githubusercontent.com/assets/3416487/6284042/82fd1c3c-b8ec-11e4-94a9-e3175967391b.png>
(The yellow ¡¶ is like a character that can be deleted ¡V and with it the comment)

¡X

**Comment by jdittrich** [comment]
I tried to have a look at the problem on my own cause my org could not provide funding. However, I could not find out, how the comments are deleted in the first place. Could you give me a hint?

**Comment by jdittrich** [comment]
o.k. just found out that while the browser is open the comments are just not displayed instead of being removed.

**Comment by JohnMcLear** [comment]
The conundrum here is "who" can delete comments..  They should be deletable by anyone I guess as they will always remain in previous versions of a pad.

**Comment by jdittrich** [comment]
Delete for everyone: Yes. 

I tried to implement a removal function for comments myself, however they seem to be created by 
 ```
ace.ace_performSelectionChange(rep.selStart,rep.selEnd,true);
ace.ace_setAttributeOnSelection('comment', commentId); 
```
And I could not find out how to revert these, since both functions are sorta undocumented.

**Comment by JohnMcLear** [comment]
Well deleting comment would delete all replies too.  Might make sense to delete a comment reply first?

On 22 May 2015 16:55, jdittrich <notifications@github.com> wrote:

Delete for everyone: Yes.

I tried to implement a removal function for comments myself, however they seem to be created by

ace.ace_performSelectionChange(rep.selStart,rep.selEnd,true);
ace.ace_setAttributeOnSelection('comment', commentId);


And I could not find out how to revert these, since both functions are sorta undocumented.

**Comment by JohnMcLear** [comment]
/s/set/remove would do it btw

On 22 May 2015 16:55, jdittrich <notifications@github.com> wrote:

Delete for everyone: Yes.

I tried to implement a removal function for comments myself, however they seem to be created by

ace.ace_performSelectionChange(rep.selStart,rep.selEnd,true);
ace.ace_setAttributeOnSelection('comment', commentId);


And I could not find out how to revert these, since both functions are sorta undocumented.

**Comment by kentonv** [comment]
> Doable but will need funding / sponsorship as I'm fully booked up doing bug fixes

How much? :)

**Comment by JohnMcLear** [comment]
Few hours to do code, an hour on test coverage so US ~$250

**Comment by kentonv** [comment]
> Few hours to do code, an hour on test coverage so US ~$250

OK, Sandstorm will be happy to sponsor. Where do we send payment? (Or e-mail kenton@sandstorm.io with details.)

**Comment by jdittrich** [comment]
I checked out the master and was happy to see that the feature works (thanks, @JohnMcLear, @kentonv) – shall we close this?

**Comment by JohnMcLear** [comment]
Can be closed.
