### ISSUE TITLE
usability/UI: Replys and Changes

### ISSUE THREAD

**Issue by jdittrich** [JohnMcLear/ep_comments#48]
Several minor-to-medium usability problems. Non of them is likely to cause severe breakdowns, however they hinder flow and intuitive understanding

I would try to take on these myself, but maybe I oversaw some technical reasons for these, so I file them here in case they need to be discussed before: 

1. Replies can be added by entering text in a textbox below current replies. It would be good to provide some context to the textbox to ease its usage – a label above stating *Your Reply (hit ENTER to send)* would make sense and it would fit the layout.
2. When suggesting a change, the currently selected text (the candidate for the change) is visible, labeled "From:" This is a great help for the user. <br> A quirk here is  that this text is placed in a textarea field. It is inactive (so it can’t be changed) but the control suggests that it could be changed (and is inactive because some mode is toggled). So some non-input element (a paragraph, styled differently than the interface’s lables) would conform to interfaces standards and is thus likely to be easily understood.
3. If "suggest change" is checked, the checkbox jumps to the bottom of the comments field, while the *from* and *to* textareas appear above. It would be visually more consistent and easier to uncheck the control again (after accidentally checking it) if the checkbox and its label would remain in place while the textareas appear below it. +1 if from/to and the checkbox are in a fieldset (or other wrapper) to connect them semantically as well as visually.

**Comment by JohnMcLear** [comment]
"Replies can be added by entering text in a textbox below current replies" -- Agreed - something I'm working on this week hopefully

"A quirk here is that this text is placed in a textarea field." - Happy for you to make this change

If "suggest change" is checked, the checkbox jumps to the bottom of the comments field, - Happy for you to make this change

**Comment by jdittrich** [comment]
...fixed 2. (Textarea to p) , though seemingly the ejs templates have some trouble with nesting elements. Could program around that though.

**Comment by JohnMcLear** [comment]
@jdittrich you sending a pull request with the fixes in?

**Comment by jdittrich** [comment]
yes; noticed that `.html(` may create security problems, needed to rework it.

**Comment by jdittrich** [comment]
request send

**Comment by JohnMcLear** [comment]
huh??

**Comment by JohnMcLear** [comment]
Is this now resolved @jdittrich  ?

**Comment by jdittrich** [comment]
Yes, we can close this.
