### ISSUE TITLE
Bug: reset suggestion UI

### ISSUE THREAD

**Issue by jdittrich** [JohnMcLear/ep_comments#49]
Reproduce this: 
1. Mark some text, 
2. click "Add Comment"
3. interact with the comment Dialog, check "Include suggested change"
4. click cancel
5. repeat 1. and .2.

What should happen: 
* The from/to fields should not be visible (works not)
* If "Include suggested change" is checked, "From" should contain the currently selected text. 

What happens instead: 
* Though the checkbox for "Include suggested change" is unchecked, the from/to fields are visible if they have been activated when calling the dialog previously.
* If "Include suggested change" is checked, "From" does not  contain the currently selected text, but is blank

**Comment by JohnMcLear** [comment]
@jdittrich you taking this on?

**Comment by jdittrich** [comment]
hmm, dunno – I assume a reset structure is already in place. You are probably way quicker. But: it would accelerate/ease it if you could point out the current place where you think the resets should/may happen (I don’t get the structure yet, partly because extensions are a bit tricky to debug (or I am doing it wrong))

**Comment by lpagliari** [comment]
Fixed by a82f171
