### ISSUE TITLE
Comment can't be deleted

### ISSUE THREAD

**Issue by lsowen** [JohnMcLear/ep_comments#52]
I am using the latest version (``0.0.22``) with etherpad ``1.5.6``.  On one pad, I have one comment which can't be deleted.  Clicking the "delete" button fires the message back to the server, and I don't receive any errors on the server, but the comment persists.

Any suggestions for debugging and/or manually removing the comment?

**Comment by JohnMcLear** [comment]
I just published 0.0.23, give that a go..

**Comment by lsowen** [comment]
Still exhibits the same behavior (message sent to server, no server error messages, but the comment isn't removed).

![comment_issue](https://cloud.githubusercontent.com/assets/1014577/8189297/6458a2a4-1429-11e5-946a-8f8a704e69df.png)

Unfortunately I had to blur out all the text.

The only entry in the server log is ``[INFO] ueberDB - Flushed 3 values``.

**Comment by JohnMcLear** [comment]
Can you provide steps to replicate the issue on a new pad please?

**Comment by lsowen** [comment]
John,

Good thinking.  I was able to replicate the issue:

1. Start a new pad
2. Create either an unordered or ordered list
3. Highlight part of one line of the list
4. Create a comment
5. Attempt to delete the comment

Let me know if you need additional information to attempt to duplicate the issue.

**Comment by JohnMcLear** [comment]
Confirmed, will sort tonight hopefully.

**Comment by JohnMcLear** [comment]
Donations welcome http://etherpad.org

**Comment by lsowen** [comment]
@JohnMcLear Looks like there is a similar issue when comments are placed on headers created by ``ep_headers2``.  Steps to recreate:

1. Start a new pad
2. Create a line and assign a header style
3. Add a comment to a portion of the line
4. Attempt to delete the comment

**Comment by JohnMcLear** [comment]
If that's teh case its probably an ep_headers2 bug as it uses divs where it should not...

I don't see ep_headers2 though..

**Comment by lsowen** [comment]
Sorry, not `ep_headers2``, ``headings2``:  https://github.com/johnmclear/ep_headings2

**Comment by JohnMcLear** [comment]
hrm, weird, okay will test.

**Comment by JohnMcLear** [comment]
Confirmed..  Gah

**Comment by JohnMcLear** [comment]
Solved :) https://github.com/JohnMcLear/ep_comments/commit/f838d3e535c5eeb9e462c842973cbff9af46bc96

**Comment by JohnMcLear** [comment]
Contributions welcome at http://etherpad.org
