### ISSUE TITLE
Modal displays part of reply form

### ISSUE THREAD

**Issue by lpagliari** [JohnMcLear/ep_comments#59]
Comment modal is displaying part of the "suggested change" form.

To reproduce:
1. Check setting to "Show Comments";
2. On any comment, check "Include suggested change";
3. Uncheck setting to "Show Comments";
4. Display modal of the comment of step 2;

Expected:
![image](https://cloud.githubusercontent.com/assets/836386/8233488/e415f684-15ac-11e5-8661-9618f7b04ce6.png)

Actual:
![image](https://cloud.githubusercontent.com/assets/836386/8233440/a88700f4-15ac-11e5-8ad6-fc09d0b2c697.png)

Note: simply adding `.comment-modal form.comment-reply .reply-suggestion,` to this code on `comment.css` 
```
/* hide comment elements when displayed on modal, not on sidebar */
 .comment-modal .reply-comment-suggest,
 .comment-modal .comment-reply-input-label,
.comment-modal form.comment-reply .reply-suggestion,
 .comment-modal input,
 .comment-modal .comment-changeTo-approve{
   display:none;
```
does not work because we're using `show()`/`hide()` to display `.reply-suggestion`. So this needs a deeper investigation.

**Comment by JohnMcLear** [comment]
@lpagliari is this something I can assign to you?

**Comment by lpagliari** [comment]
I won't be able to work on this right now, but can take a look later.

**Comment by JohnMcLear** [comment]
Later is fine :) thanks!

On 18 Jun 2015 18:50, Luiza Pagliari <notifications@github.com> wrote:

I won't be able to work on this right now, but can take a look later.
