### ISSUE TITLE
comments not displayed in Firefox

### ISSUE THREAD

**Issue by Cyrille37** [JohnMcLear/ep_comments#78]
Hi
The plugin works fine with Chromium but not with Firefox. Firefox permits to create comment but they are not displayed.
Cheers.

**Comment by lpagliari** [comment]
Can you provide more details? It is working on my instance on FF, Chrome, and Safari. Did you get any error/warning on the console?

**Comment by Cyrille37** [comment]
No special thing.
FireFox 41.0 on Ubuntu 14.04 LTS

**Comment by jdittrich** [comment]
can we close this?
