### ISSUE TITLE
Publish latest version of this plugin on npm

### ISSUE THREAD

**Issue by milan-w** [JohnMcLear/ep_comments#88]
Hi John!

Would you please publish the latest version of this plugin on npm?
We manage most of our dependencies this way and it would be awesome if we could use all of the improvements you and the other contributors made in the last 10 months without resorting to github pulls.

Thanks a bunch!
Cheers, 
Milan

**Comment by JohnMcLear** [comment]
Done.  Sorry I have been really busy

**Comment by JohnMcLear** [comment]
```
jose@PBOH-SNUG:~/ep_comments$ npm publish
+ ep_comments_page@0.0.33
```
