### ISSUE TITLE
Comment Icon not shown, chat frame overlaps comment field

### ISSUE THREAD

**Issue by Flauschie** [JohnMcLear/ep_comments#89]
The comment icon which can be activated via its appropriate function won't be shown and the comment field is being overlapped by the chat frame.

I have added the settings at the end of my settings.json. Highlighting works.

```
{ ...
  // Display comments as icons, not boxes
  "ep_comments_page": {
    "displayCommentAsIcon": true
  },
  // Highlight selected text when adding comment
  "ep_comments_page": {
    "highlightSelectedText": true
  }
}
```

EDIT: both "ep_page_view" and "ep_comments_page" were installed via npm install (no git clone involved)

EDIT2: Added pictures for clarification

![comment_bug_01](https://cloud.githubusercontent.com/assets/4295187/14943965/1787c0f8-0fe7-11e6-8527-bbc0a770f935.PNG)
![comment_bug_02](https://cloud.githubusercontent.com/assets/4295187/14943966/1787c1a2-0fe7-11e6-94aa-69921b07aa71.PNG)
![comment_bug_03](https://cloud.githubusercontent.com/assets/4295187/14943967/178822c8-0fe7-11e6-91ff-1df3efb570f0.PNG)

**Comment by lpagliari** [comment]
Your second "ep_comments_page": {...} is overwriting the first one. You
need to place both properties on the same block if you want both turned on:

"ep_comments_page": {
"displayCommentAsIcon": true,
"highlightSelectedText": true
}

Regarding the chat window, if you are not using the chat feature, it is
possible to turn it off on Etherpad settings (I don't remember which one
now, but it's on the documentation, I guess).

Hope this helps. :-)

**Comment by Flauschie** [comment]
Oh my god. I should go to bed. Too much work done today. Thank you very much for your help, I appreciate it!!!

**Comment by Billaboong** [comment]
I am not also able to see the comments Icon as they are no being rendered properly....I am using the displayCommentAsIcon setting.
Attached image is how the icon is showing.

![etherpad_comments_error](https://user-images.githubusercontent.com/4427236/28906931-dac1311c-7823-11e7-874b-db359442f880.png)

**Comment by lpagliari** [comment]
@Billaboong there are two things you might need to consider:

- the Etherpad version you're using: please make sure you have at least [version 1.5.7](https://github.com/ether/etherpad-lite/commit/1353c093dbad9514c50ce81fcc806ad93d25ae03);
- make sure you [clear your browsing data](https://github.com/ether/ep_comments/pull/46#issuecomment-111514367), so icons are reloaded.
