### ISSUE TITLE
Does not use translation

### ISSUE THREAD

**Issue by rugk** [JohnMcLear/ep_comments#91]
As I see the [German translation](https://github.com/JohnMcLear/ep_comments/blob/master/locales/de.json) is included in the repo, but it is not used in my installation.
Plugin version:  0.0.33
Etherpad v1.6.0

In Firefox (v43) it also shows me this:
> Could not find string ep_comments_page.time.minutes.past html10n.js:742:1
Couldn't find translation key ep_comments_page.delete_comment.title html10n.js:831:1
Couldn't find translation key ep_comments_page.comments_template.from html10n.js:831:1
Couldn't find translation key ep_comments_page.comments_template.suggested_change html10n.js:831:1
Couldn't find translation key ep_comments_page.comments_template.accept_change.value html10n.js:831:1
Couldn't find translation key ep_comments_page.comments_template.reply_input_label html10n.js:831:1
Couldn't find translation key ep_comments_page.comments_template.include_suggestion html10n.js:831:1
Couldn't find translation key ep_comments_page.comments_template.from html10n.js:831:1
Couldn't find translation key ep_comments_page.comments_template.to html10n.js:831:1
Couldn't find translation key ep_comments_page.delete_comment.title[...]

**Comment by lpagliari** [comment]
Working here:
![image](https://cloud.githubusercontent.com/assets/836386/15048529/613fbcf6-12c0-11e6-9440-4947b4f65729.png)

Tested on both Chrome and Firefox, on a Mac. @rugk , can you provide more details about the environment you are testing at, please? Did you try restarting the server?

**Comment by rugk** [comment]
>  Did you try restarting the server?

Good suggestion. After restarting it worked...
However this is strange as I installed the plugin via the admin panel and I thought there everything should be handled, so that it works.
Other plugins also do not need a manual restart.

**Comment by lpagliari** [comment]
I'm not very familiar with the part of the code where Etherpad installs plugins and reloads their contents, but I've suggested restarting the server because I had the same issue before when the .json file was created after the server was started. Maybe this is an issue of that part of Etherpad code...

**Comment by rugk** [comment]
Mhh, okay. I've opened an issue there...
